version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "09:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  ignore:
  - dependency-name: husky
    versions:
    - 5.1.2
  - dependency-name: snyk
    versions:
    - 1.463.0
