name: coverage
on:
  push:
    branches: [master]
  pull_request_target:
    types: [opened, reopened, synchronize]

jobs:
  Coverage-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          threshold: 90
          skip-step: install
