name: coverage
on:
  push:
    branches: [master]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  Coverage-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ArtiomTr/jest-coverage-report-action@v2.1.3
        with:
          #coverage-file: ./test_reports/report.json
          # base-coverage-file: coverage/report-final.json
          test-script: npm test
          threshold: 90
